# Generated by Django 5.0.3 on 2024-03-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_login_profile_registration'),
        ('polls', '0002_rename_task_post_login_profile_registration'),
    ]

    operations = [
    ]
